const GalaxyPhones = {
    "갤럭시 S25 울트라": {
        mainImage: "./assets/images/GalaxyS/Galaxy_S25U_Silverblue.png",
        mainPrice: 1698400,
        colors: [
            { name: "티타늄 실버블루", code: "#8e9fbc", image: "./assets/images/GalaxyS/Galaxy_S25U_Silverblue.png" },
            { name: "티타늄 그레이", code: "#b3ab9e", image: "./assets/images/GalaxyS/Galaxy_S25U_Grey.png" },
            { name: "티타늄 블랙", code: "#4a4a4d", image: "./assets/images/GalaxyS/Galaxy_S25U_Black.png" },
            { name: "티타늄 화이트실버", code: "#d9d9d6", image: "./assets/images/GalaxyS/Galaxy_S25U_Whitesilver.png" },
        ],
        discount: 20000,
        storage: { 
            "256GB": 1698400,
            "512GB": 1841400,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 S25 플러스": {
        mainImage: "./assets/images/GalaxyS/Galaxy_S25P_Navy.png",
        mainPrice: 1353000,
        colors: [
            { name: "네이비", code: "#3c5b8a", image: "./assets/images/GalaxyS/Galaxy_S25P_Navy.png" },
            { name: "아이스 블루", code: "#c8d3df", image: "./assets/images/GalaxyS/Galaxy_S25P_Iceblue.png" },
            { name: "실버 쉐도우", code: "#7f7f7e", image: "./assets/images/GalaxyS/Galaxy_S25P_Silvershadow.png" },
            { name: "민트", code: "#d3e8dd", image: "./assets/images/GalaxyS/Galaxy_S25P_Mint.png" },
        ],
        discount: 20000,
        storage: {
            "256GB": 1353000,
            "512GB": 1496000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 S25": {
        mainImage: "./assets/images/GalaxyS/Galaxy_S25_Navy.png",
        mainPrice: 1155000,
        colors: [
            { name: "네이비", code: "#3c5b8a", image: "./assets/images/GalaxyS/Galaxy_S25_Navy.png" },
            { name: "아이스 블루", code: "#c8d3df", image: "./assets/images/GalaxyS/Galaxy_S25_Iceblue.png" },
            { name: "실버 쉐도우", code: "#7f7f7e", image: "./assets/images/GalaxyS/Galaxy_S25_Silvershadow.png" },
            { name: "민트", code: "#d3e8dd", image: "./assets/images/GalaxyS/Galaxy_S25_Mint.png" },
        ],
        discount: 20000,
        storage: {
            "256GB": 1155000,
            "512GB": 1298000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 S24 울트라": {
        mainImage: "./assets/images/GalaxyS/Galaxy_S24U_Grey.png",
        mainPrice: 1698400,
        colors: [
            { name: "티타늄 그레이", code: "#ACA49B", image: "./assets/images/GalaxyS/Galaxy_S24U_Grey.png" },
            { name: "티타늄 옐로우", code: "#F0E1B9", image: "./assets/images/GalaxyS/Galaxy_S24U_Yellow.png" },
            { name: "티타늄 바이올렛", code: "#4D4E5F", image: "./assets/images/GalaxyS/Galaxy_S24U_Violet.png" },
            { name: "티타늄 블랙", code: "#62605F", image: "./assets/images/GalaxyS/Galaxy_S24U_Black.png" }
        ],
        discount: 20000,
        storage: { "256GB": 1698400 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 S24 플러스": {
        mainImage: "./assets/images/GalaxyS/Galaxy_S24P_Cobaltviolet.png",
        mainPrice: 1353000,
        colors: [
            { name: "코발트 바이올렛", code: "#52566D", image: "./assets/images/GalaxyS/Galaxy_S24P_Cobaltviolet.png" },
            { name: "앰버 옐로우", code: "#F1EAD4", image: "./assets/images/GalaxyS/Galaxy_S24P_Amberyellow.png" },
            { name: "마블 그레이", code: "#C5C3C3", image: "./assets/images/GalaxyS/Galaxy_S24P_Marblegrey.png" },
            { name: "오닉스 블랙", code: "#4A4A4D", image: "./assets/images/GalaxyS/Galaxy_S24P_Onyxblack.png" },
        ],
        discount: 20000,
        storage: { "256GB": 1353000 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 S24 FE": {
        mainImage: "./assets/images/GalaxyS/Galaxy_S24F_Blue.png",
        mainPrice: 946000,
        colors: [
            { name: "블루", code: "#BCD5EA", image: "./assets/images/GalaxyS/Galaxy_S24F_Blue.png" },
            { name: "그라파이트", code: "#44484B", image: "./assets/images/GalaxyS/Galaxy_S24F_Graphite.png" },
            { name: "그레이", code: "#C5C3C3", image: "./assets/images/GalaxyS/Galaxy_S24F_Grey.png" },
            { name: "옐로우", code: "#EEE29C", image: "./assets/images/GalaxyS/Galaxy_S24F_Yellow.png" },
        ],
        discount: 20000,
        storage: { "256GB": 946000 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 S24": {
        mainImage: "./assets/images/GalaxyS/Galaxy_S24_Cobaltviolet.png",
        mainPrice: 1155000,
        colors: [
            { name: "코발트 바이올렛", code: "#52566D", image: "./assets/images/GalaxyS/Galaxy_S24_Cobaltviolet.png" },
            { name: "엠버 옐로우", code: "#F1EAD4", image: "./assets/images/GalaxyS/Galaxy_S24_Amberyellow.png" },
            { name: "마블 그레이", code: "#C5C3C3", image: "./assets/images/GalaxyS/Galaxy_S24_Marblegrey.png" },
            { name: "오닉스 블랙", code: "#4A4A4D", image: "./assets/images/GalaxyS/Galaxy_S24_Onyxblack.png" },
        ],
        discount: 20000,
        storage: { "256GB": 1155000 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 Z플립6": {
        mainImage: "./assets/images/GalaxyZ/Galaxy_ZFlip6_Blue.png",
        mainPrice: 1485000,
        colors: [
            { name: "블루", code: "#BCD5EA", image: "./assets/images/GalaxyZ/Galaxy_ZFlip6_Blue.png" },
            { name: "실버 쉐도우", code: "#7E7E7E", image: "./assets/images/GalaxyZ/Galaxy_ZFlip6_Silvershadow.png" },
            { name: "옐로우", code: "#F8E59A", image: "./assets/images/GalaxyZ/Galaxy_ZFlip6_Yellow.png" },
            { name: "민트", code: "#A5DFD3", image: "./assets/images/GalaxyZ/Galaxy_ZFlip6_Mint.png" },
        ],
        discount: 20000,
        storage: { "256GB": 1485000 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 Z플립5": {
        mainImage: "./assets/images/GalaxyZ/Galaxy_ZFlip5_Graphite.png",
        mainPrice: 1300200,
        colors: [
            { name: "그라파이트", code: "#53565A", image: "./assets/images/GalaxyZ/Galaxy_ZFlip5_Graphite.png" },
            { name: "크림", code: "#F0EAE0", image: "./assets/images/GalaxyZ/Galaxy_ZFlip5_Cream.png" },
            { name: "라벤더", code: "#D4C7D9", image: "./assets/images/GalaxyZ/Galaxy_ZFlip5_Lavender.png" },
            { name: "민트", code: "#CAD9D3", image: "./assets/images/GalaxyZ/Galaxy_ZFlip5_Mint.png" },
        ],
        discount: 20000,
        storage: { "256GB": 1300200 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 Z폴드6": {
        mainImage: "./assets/images/GalaxyZ/Galaxy_ZFold6_Pink.png",
        mainPrice: 2229700,
        colors: [
            { name: "핑크", code: "#F0DBE1", image: "./assets/images/GalaxyZ/Galaxy_ZFold6_Pink.png" },
            { name: "실버 쉐도우", code: "#7F7F7E", image: "./assets/images/GalaxyZ/Galaxy_ZFold6_Silvershadow.png" },
            { name: "네이비", code: "#485167", image: "./assets/images/GalaxyZ/Galaxy_ZFold6_Navy.png" },
        ],
        discount: 20000,
        storage: { "256GB": 2229700 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 Z폴드5": {
        mainImage: "./assets/images/GalaxyZ/Galaxy_ZFold5_Cream.png",
        mainPrice: 2097700,
        colors: [
            { name: "크림", code: "#F0EAE0", image: "./assets/images/GalaxyZ/Galaxy_ZFold5_Cream.png" },
            { name: "아이스 블루", code: "#A6AFC2", image: "./assets/images/GalaxyZ/Galaxy_ZFold5_Iceblue.png" },
            { name: "팬텀 블랙", code: "#211E16", image: "./assets/images/GalaxyZ/Galaxy_ZFold5_Phantomblack.png" },
        ],
        discount: 20000,
        storage: { "256GB": 2097700 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 A24": {
        mainImage: "./assets/images/GalaxyA/Galaxy_A24_Black.png",
        mainPrice: 396000,
        colors: [
            { name: "블랙", code: "#3B3D3F", image: "./assets/images/GalaxyA/Galaxy_A24_Black.png" },
            { name: "다크 레드", code: "#694955", image: "./assets/images/GalaxyA/Galaxy_A24_Darkred.png" },
            { name: "라이트 그린", code: "#C1D1A6", image: "./assets/images/GalaxyA/Galaxy_A24_Lightgreen.png" },
        ],
        discount: 20000,
        storage: { "128GB": 396000 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 A25": {
        mainImage: "./assets/images/GalaxyA/Galaxy_A25_Blueblack.png",
        mainPrice: 449900,
        colors: [
            { name: "블루 블랙", code: "#3F4251", image: "./assets/images/GalaxyA/Galaxy_A25_Blueblack.png" },
            { name: "라이트 블루", code: "#DDE5ED", image: "./assets/images/GalaxyA/Galaxy_A25_Lightblue.png" },
            { name: "옐로우", code: "#E7E9A5", image: "./assets/images/GalaxyA/Galaxy_A25_Yellow.png" },
        ],
        discount: 20000,
        storage: { "128GB": 449900 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 A35": {
        mainImage: "./assets/images/GalaxyA/Galaxy_A35_Navy.png",
        mainPrice: 469900, 
        colors: [
            { name: "어썸 네이비", code: "#3E424B", image: "./assets/images/GalaxyA/Galaxy_A35_Navy.png" },
            { name: "어썸 아이스블루", code: "#CBD9E7", image: "./assets/images/GalaxyA/Galaxy_A35_Iceblue.png" },
            { name: "어썸 라일락", code: "#C0BDD1", image: "./assets/images/GalaxyA/Galaxy_A35_Lilac.png" },
        ],
        discount: 20000,
        storage: { "128GB": 469900 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "갤럭시 Quantum5": {
        mainImage: "./assets/images/GalaxyA/Galaxy_Quantum5_Navy.png",
        mainPrice: 618200,
        colors: [
            { name: "어썸 네이비", code: "#3E424B", image: "./assets/images/GalaxyA/Galaxy_Quantum5_Navy.png" },
            { name: "어썸 아이스블루", code: "#CBD9E7", image: "./assets/images/GalaxyA/Galaxy_Quantum5_Iceblue.png" },
            { name: "어썸 라일락", code: "#C0BDD1", image: "./assets/images/GalaxyA/Galaxy_Quantum5_Lilac.png" },
        ],
        discount: 20000,
        storage: { "128GB": 618200 },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },
}

export default GalaxyPhones;