const IPhones = {
    "아이폰 16e": {
        mainImage: "./assets/images/Iphone/Iphone_16e_Black.png",
        mainPrice: 990000,
        colors: [
            { name: "블랙", code: "#4b4e51", image: "./assets/images/Iphone/Iphone_16e_Black.png" },
            { name: "화이트", code: "#fafafa", image: "./assets/images/Iphone/Iphone_16e_White.png" },
        ],
        discount: 20000,
        storage: {
            "128GB": 990000,
            "256GB": 1133000,
            "512GB": 1430000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "아이폰 16 Pro Max": {
        mainImage: "./assets/images/Iphone/Iphone_16PM_Desert.png",
        mainPrice: 1892000,
        colors: [
            { name: "데저트 티타늄", code: "#bfa48f", image: "./assets/images/Iphone/Iphone_16PM_Desert.png" },
            { name: "네추럴 티타늄", code: "#c2bcb2", image: "./assets/images/Iphone/Iphone_16PM_Natural.png" },
            { name: "화이트 티타늄", code: "#f2f1ed", image: "./assets/images/Iphone/Iphone_16PM_White.png" },
            { name: "블랙 티타늄", code: "#3c3c3d", image: "./assets/images/Iphone/Iphone_16PM_Black.png" },
        ],
        discount: 20000,
        storage: {
            "256GB": 1892000,
            "512GB": 2200000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },
    
    "아이폰 16 Pro": {
        mainImage: "./assets/images/Iphone/Iphone_16PR_Desert.png",
        mainPrice: 1540000,
        colors: [
            { name: "데저트 티타늄", code: "#bfa48f", image: "./assets/images/Iphone/Iphone_16PR_Desert.png" },
            { name: "네추럴 티타늄", code: "#c2bcb2", image: "./assets/images/Iphone/Iphone_16PR_Natural.png" },
            { name: "화이트 티타늄", code: "#f2f1ed", image: "./assets/images/Iphone/Iphone_16PR_White.png" },
            { name: "블랙 티타늄", code: "#3c3c3d", image: "./assets/images/Iphone/Iphone_16PR_Black.png" },
        ],
        discount: 20000,
        storage: {
            "128GB": 1540000,
            "256GB": 1694000,
            "512GB": 1991000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },
    
    "아이폰 16 Plus": {
        mainImage: "./assets/images/Iphone/Iphone_16P_Ultramarine.png",
        mainPrice: 1342000,
        colors: [
            { name: "울트라마린", code: "#9aadf6", image: "./assets/images/Iphone/Iphone_16P_Ultramarine.png" },
            { name: "틸", code: "#b0d4d2", image: "./assets/images/Iphone/Iphone_16P_Teal.png" },
            { name: "핑크", code: "#f2adda", image: "./assets/images/Iphone/Iphone_16P_Pink.png" },
            { name: "화이트", code: "#ffffff", image: "./assets/images/Iphone/Iphone_16P_White.png" },
            { name: "블랙", code: "#3c4042", image: "./assets/images/Iphone/Iphone_16P_Black.png" },
        ],
        discount: 20000,
        storage: {
            "128GB": 1342000,
            "256GB": 1496000,
            "512GB": 1793000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },
    
    "아이폰 16": {
        mainImage: "./assets/images/Iphone/Iphone_16_Ultramarine.png",
        mainPrice: 1243000,
        colors: [
            { name: "울트라마린", code: "#9aadf6", image: "./assets/images/Iphone/Iphone_16_Ultramarine.png" },
            { name: "틸", code: "#b0d4d2", image: "./assets/images/Iphone/Iphone_16_Teal.png" },
            { name: "핑크", code: "#f2adda", image: "./assets/images/Iphone/Iphone_16_Pink.png" },
            { name: "화이트", code: "#ffffff", image: "./assets/images/Iphone/Iphone_16_White.png" },
            { name: "블랙", code: "#3c4042", image: "./assets/images/Iphone/Iphone_16_Black.png" },
        ],
        discount: 20000,
        storage: {
            "128GB": 1243000,
            "256GB": 1397000,
            "512GB": 1694000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },

    "아이폰 15 Pro Max": {
        mainImage: "./assets/images/Iphone/Iphone_15PM_Natural.png",
        mainPrice: 1892000,
        colors: [
            { name: "네추럴 티타늄", code: "#c2bcb2", image: "./assets/images/Iphone/Iphone_15PM_Natural.png" },
            { name: "블루 티타늄", code: "#3d4555", image: "./assets/images/Iphone/Iphone_15PM_Blue.png" },
            { name: "화이트 티타늄", code: "#f2f1ed", image: "./assets/images/Iphone/Iphone_15PM_White.png" },
            { name: "블랙 티타늄", code: "#3c3c3d", image: "./assets/images/Iphone/Iphone_15PM_Black.png" },
        ],
        discount: 20000,
        storage: {
            "256GB": 1892000,
            "512GB": 2200000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },
    
    "아이폰 15 Pro": {
        mainImage: "./assets/images/Iphone/Iphone_15PR_Natural.png",
        mainPrice: 1892000,
        colors: [
            { name: "네추럴 티타늄", code: "#c2bcb2", image: "./assets/images/Iphone/Iphone_15PR_Natural.png" },
            { name: "블루 티타늄", code: "#3d4555", image: "./assets/images/Iphone/Iphone_15PR_Blue.png" },
            { name: "화이트 티타늄", code: "#f2f1ed", image: "./assets/images/Iphone/Iphone_15PR_White.png" },
            { name: "블랙 티타늄", code: "#3c3c3d", image: "./assets/images/Iphone/Iphone_15PR_Black.png" },
        ],
        discount: 20000,
        storage: {
            "128GB": 1540000,
            "256GB": 1694000,
            "512GB": 1991000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },
    
    "아이폰 15 Plus": {
        mainImage: "./assets/images/Iphone/Iphone_15P_Blue.png",
        mainPrice: 1342000,
        colors: [
            { name: "블루", code: "#d5dde0", image: "./assets/images/Iphone/Iphone_15P_Blue.png" },
            { name: "핑크", code: "#ebd0d2", image: "./assets/images/Iphone/Iphone_15P_Pink.png" },
            { name: "옐로", code: "#ece6c6", image: "./assets/images/Iphone/Iphone_15P_Yellow.png" },
            { name: "그린", code: "#cfd9c9", image: "./assets/images/Iphone/Iphone_15P_Green.png" },
            { name: "블랙", code: "#3c4042", image: "./assets/images/Iphone/Iphone_15P_Black.png" },
        ],
        discount: 20000,
        storage: {
            "128GB": 1342000,
            "256GB": 1496000,
            "512GB": 1793000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },
    
    "아이폰 15": {
        mainImage: "./assets/images/Iphone/Iphone_15_Blue.png",
        mainPrice: 1243000,
        colors: [
            { name: "블루", code: "#d5dde0", image: "./assets/images/Iphone/Iphone_15P_Blue.png" },
            { name: "핑크", code: "#ebd0d2", image: "./assets/images/Iphone/Iphone_15P_Pink.png" },
            { name: "옐로", code: "#ece6c6", image: "./assets/images/Iphone/Iphone_15P_Yellow.png" },
            { name: "그린", code: "#cfd9c9", image: "./assets/images/Iphone/Iphone_15P_Green.png" },
            { name: "블랙", code: "#3c4042", image: "./assets/images/Iphone/Iphone_15P_Black.png" },
        ],
        discount: 20000,
        storage: {
            "128GB": 1243000,
            "256GB": 1397000,
            "512GB": 1694000,
        },
        telecom: ["SKT", "KT", "LG U+"],
        type: ["번호이동", "기기변경"],
        monthly: ["24개월", "30개월", "36개월"],
        sale: ["공시지원할인", "선택약정할인"],
        service: ["제휴카드 할인", "결합 할인", "복지 할인"],
        internet: ["상담신청", "신청안함"],
    },
}

export default IPhones;